export default async function handler(req, res) {
  // Only allow POST
  if (req.method !== 'POST') {
    return res.status(405).json({
      code: 'METHOD_NOT_ALLOWED',
      message: 'Only POST requests are allowed.'
    });
  }

  // Validate prompt
  const { prompt, platform = 'youtube' } = req.body;
  if (!prompt) {
    return res.status(400).json({
      code: 'PROMPT_REQUIRED',
      message: 'Prompt is required.'
    });
  }

  // Check for OpenAI API key
  const openaiApiKey = process.env.OPENAI_API_KEY;
  if (!openaiApiKey) {
    return res.status(500).json({
      code: 'OPENAI_API_KEY_MISSING',
      message: 'OpenAI API key not configured.'
    });
  }

  try {
    // Call OpenAI DALL-E API
    const response = await fetch('https://api.openai.com/v1/images/generations', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${openaiApiKey}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        model: 'dall-e-3',
        prompt: prompt,
        size: platform === 'instagram' ? '1024x1792' : '1792x1024',
        quality: 'standard',
        n: 1
      })
    });

    const data = await response.json();

    // Handle OpenAI errors
    if (!response.ok) {
      return res.status(response.status).json({
        code: 'OPENAI_API_ERROR',
        message: data.error?.message || 'OpenAI API error.',
        details: data
      });
    }

    // Handle missing image
    if (!data.data || !data.data[0] || !data.data[0].url) {
      return res.status(502).json({
        code: 'IMAGE_NOT_GENERATED',
        message: 'Image was not generated by OpenAI.',
        details: data
      });
    }

    // Success
    return res.status(200).json({
      success: true,
      imageUrl: data.data[0].url,
      prompt: prompt,
      platform: platform
    });

  } catch (error) {
    // Catch-all server error
    return res.status(500).json({
      code: 'SERVER_ERROR',
      message: 'Unexpected server error.',
      details: error.message
    });
  }
}
